### ISSUE TITLE
typo and question

### ISSUE THREAD

**Issue by ngawangtrinley** [marcusklang/docforia#3]
## typo
`flattend` --> `flattened` in https://github.com/marcusklang/docforia/tree/master#why

## question
Are you using this in a project? Are there newer/better alternatives?

**Comment by marcusklang** [comment]
Thanks, will fix it, might change the frontpage in response to your question:

I do use it but only for compatibility reasons. All my newer projects use Docria, https://github.com/marcusklang/docria

In my mind it is better in essentially every way. Docria was initially created to enable interoperability between Java and Python, to try to get the best of both worlds. It forced me to simplify the implementation as I had to main two parallel implementations. The idea was quick and dirty code in Python for debugging, machine learning and prototyping, and efficient information extraction using Java/Scala with Apache Spark. The Python library also has extensions for Jupyter Notebooks, which using a few lines of code produce a presentation of the data contained within a document.

Docria is slightly stricter than Docforia in that it requires the user to specify in advance which fields should exist within a layer. This requirement of specifying fields helps with automatic presentation, validation, and consistency checks. Fields and layer definitions can still be changed but any change is checked to enforce consistency.

**Comment by ngawangtrinley** [comment]
Thanks a lot for the quick answer. Docria looks really good. Just out of curiosity, what would you say is the advantage of Docria over a format like [folia](https://proycon.github.io/folia/)?

**Comment by marcusklang** [comment]
It comes down to flexibility, scale and efficiency.

Docria was design to deal with millions of documents, and as such efficiency is slightly more important than in FoLiA.

Concretely, right now would be:

- Flexible, its dynamic schema allows to represent structures not present in the FoLiA specification
- Partial deserialization, Docrias binary format allows for fast document filtering based on properties without having to actually decode the entire document. XML does not need to reconstruct the document, but it still has to parse through it which adds overhead. Future improvements will include the ability to extract a selection of layers, even harder with XML.
- Lower storage requirements when uncompressed, about 10x less than XML depending on data, and 2-3x when compressed. This also correlates to I/O overhead and decompression which with my measurements are more significant than size.
- Forgiving, noisy web texts can be encoded, referenced with spans without normalization. Something I was unable to do with FoLiA, XML was the primary roadblock. XML does not allow certain characters, and whitespace might complicate things. Moving from Python to Java also breaks multilingual offsets in XML (must be converted to runtime offsets), this is managed by the Docria library and in the format.

**Comment by ngawangtrinley** [comment]
Wonderful. Do you have examples of real life projects where you use this? 

I'll play a bit with it and look at the documentation and I'll probably have more questions.

**Comment by marcusklang** [comment]
Langforia is one project that uses Docforia. Docria is used internally in research projects for storing and enriching Wikipedia dumps. Dumps which have been used by students in project courses for various information extraction tasks.
